import Database from "better-sqlite3";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

const oldDbPath = resolve("OLD/iscatdns/database.db");
const outputPath = resolve("migrations/import-old-data.sql");

if (!existsSync(oldDbPath)) {
  console.log(`No old database found at ${oldDbPath}. Nothing to migrate.`);
  process.exit(0);
}

const db = new Database(oldDbPath, { readonly: true });
const sql: string[] = [
  "-- Generated by scripts/migrate-old-sqlite.ts",
  "-- Existing bcrypt passwords are marked as legacy-bcrypt; users must reset passwords by email.",
  "PRAGMA foreign_keys = OFF;",
  "BEGIN TRANSACTION;",
];

const users = readAll<Record<string, unknown>>("SELECT * FROM users");
for (const user of users) {
  sql.push(
    `INSERT OR IGNORE INTO users (id, username, email, password_hash, password_salt, role, email_verified_at, telegram_user_id, created_at, updated_at) VALUES (${values([
      `usr_old_${user.id}`,
      user.username,
      user.email || `${user.username}@legacy.invalid`,
      user.password,
      "legacy-bcrypt",
      user.role || "user",
      user.is_verified ? user.created_at || new Date().toISOString() : null,
      user.telegram_user_id || null,
      user.created_at || new Date().toISOString(),
      user.created_at || new Date().toISOString(),
    ])});`,
  );
}

const records = readAll<Record<string, unknown>>("SELECT * FROM dns_records");
for (const record of records) {
  sql.push(
    `INSERT OR IGNORE INTO dns_records (id, user_id, type, name, content, ttl, proxied, cloudflare_record_id, status, created_at, updated_at) VALUES (${values([
      record.id,
      `usr_old_${record.user_id}`,
      record.type,
      record.name,
      record.content,
      record.ttl || 3600,
      record.proxied ? 1 : 0,
      record.id,
      "active",
      record.created_at || new Date().toISOString(),
      record.created_at || new Date().toISOString(),
    ])});`,
  );
}

const applications = readAll<Record<string, unknown>>("SELECT * FROM subdomain_applications");
for (const app of applications) {
  sql.push(
    `INSERT OR IGNORE INTO applications (id, user_id, request_type, target_dns_record_id, subdomain, record_type, record_value, purpose, status, admin_notes, ttl, proxied, voting_deadline_at, telegram_message_id, created_at, updated_at) VALUES (${values([
      `app_old_${app.id}`,
      `usr_old_${app.user_id}`,
      app.request_type,
      app.target_dns_record_id || null,
      app.subdomain,
      app.record_type,
      app.record_value,
      app.purpose || "",
      normalizeApplicationStatus(String(app.status || "pending")),
      app.admin_notes || null,
      app.ttl || 3600,
      app.proxied ? 1 : 0,
      app.voting_deadline_at || new Date().toISOString(),
      app.telegram_message_id || null,
      app.created_at || new Date().toISOString(),
      app.created_at || new Date().toISOString(),
    ])});`,
  );
}

const votes = readAll<Record<string, unknown>>("SELECT * FROM application_votes");
for (const vote of votes) {
  const admin = users.find((user) => String(user.telegram_user_id || "") === String(vote.admin_telegram_user_id || ""));
  if (!admin) continue;
  sql.push(
    `INSERT OR IGNORE INTO application_votes (id, application_id, admin_user_id, admin_telegram_user_id, vote_type, source, created_at) VALUES (${values([
      `vote_old_${vote.id}`,
      `app_old_${vote.application_id}`,
      `usr_old_${admin.id}`,
      vote.admin_telegram_user_id,
      vote.vote_type === "approve" ? "approve" : "deny",
      "telegram",
      vote.created_at || new Date().toISOString(),
    ])});`,
  );
}

const reports = readAll<Record<string, unknown>>("SELECT * FROM abuse_reports");
for (const report of reports) {
  sql.push(
    `INSERT OR IGNORE INTO abuse_reports (id, subdomain, reason, details, reporter_ip, status, telegram_message_id, created_at, updated_at) VALUES (${values([
      `abr_old_${report.id}`,
      report.subdomain,
      report.reason,
      report.details || null,
      report.reporter_ip || null,
      normalizeReportStatus(String(report.status || "new")),
      report.telegram_message_id || null,
      report.created_at || new Date().toISOString(),
      report.created_at || new Date().toISOString(),
    ])});`,
  );
}

sql.push("COMMIT;", "PRAGMA foreign_keys = ON;");
mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, `${sql.join("\n")}\n`);
console.log(`Wrote ${outputPath}`);

function readAll<T>(query: string): T[] {
  try {
    return db.prepare(query).all() as T[];
  } catch {
    return [];
  }
}

function values(items: unknown[]) {
  return items.map(escapeSql).join(", ");
}

function escapeSql(value: unknown) {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "number") return Number.isFinite(value) ? String(value) : "NULL";
  return `'${String(value).replace(/'/g, "''")}'`;
}

function normalizeApplicationStatus(status: string) {
  return ["pending", "approved", "rejected", "expired", "error"].includes(status) ? status : "pending";
}

function normalizeReportStatus(status: string) {
  return ["new", "acknowledged", "resolved", "ignored"].includes(status) ? status : "new";
}
