import Database from "better-sqlite3";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

const oldDbCandidates = [
  process.env.OLD_DB_PATH,
  "OLD/database.db",
  "OLD/iscatdns/database.db",
  "old/database.db",
  "old/iscatdns/database.db",
].filter((value): value is string => Boolean(value && value.trim()));

const oldDbPath = oldDbCandidates.map((value) => resolve(value)).find((value) => existsSync(value));
const outputPath = resolve("migrations/import-old-data.sql");

if (!oldDbPath) {
  console.log(`No old database found. Checked: ${oldDbCandidates.map((value) => resolve(value)).join(", ")}`);
  process.exit(0);
}

const db = new Database(oldDbPath, { readonly: true });
const now = new Date().toISOString();
const legacyRecordIds = new Set(readAll<{ id: string }>("SELECT id FROM dns_records").map((record) => String(record.id)));
const sql: string[] = [
  "-- Generated by scripts/migrate-old-sqlite.ts",
  `-- Source database: ${oldDbPath}`,
  "-- Legacy bcrypt passwords are preserved. Users must reset passwords after migration.",
  "-- Legacy verification/reset/bind tokens are intentionally not migrated.",
  "PRAGMA foreign_keys = OFF;",
  "BEGIN TRANSACTION;",
];

const users = readAll<Record<string, unknown>>("SELECT * FROM users ORDER BY id");
for (const user of users) {
  const createdAt = asTimestamp(user.created_at) ?? now;
  sql.push(
    `INSERT OR IGNORE INTO users (id, username, email, password_hash, password_salt, role, email_verified_at, telegram_user_id, created_at, updated_at) VALUES (${values([
      `usr_old_${user.id}`,
      fallbackText(user.username, `legacy-user-${user.id}`),
      normalizeLegacyEmail(user.email, user.username, user.id),
      fallbackText(user.password, "legacy-missing-password"),
      "legacy-bcrypt",
      normalizeRole(user.role),
      null,
      nullableText(user.telegram_user_id),
      createdAt,
      createdAt,
    ])});`,
  );
}

const records = readAll<Record<string, unknown>>("SELECT * FROM dns_records ORDER BY id");
for (const record of records) {
  const createdAt = asTimestamp(record.created_at) ?? now;
  sql.push(
    `INSERT OR IGNORE INTO dns_records (id, user_id, type, name, content, ttl, proxied, cloudflare_record_id, status, created_at, updated_at) VALUES (${values([
      fallbackText(record.id, `rec_old_${Math.random().toString(16).slice(2)}`),
      `usr_old_${record.user_id}`,
      normalizeRecordType(record.type),
      fallbackText(record.name, `invalid.${createdAt}`),
      fallbackText(record.content, "0.0.0.0"),
      normalizeInteger(record.ttl, 3600),
      isTruthy(record.proxied) ? 1 : 0,
      null,
      "active",
      createdAt,
      createdAt,
    ])});`,
  );
}

const applications = readAll<Record<string, unknown>>("SELECT * FROM subdomain_applications ORDER BY id");
for (const app of applications) {
  const createdAt = asTimestamp(app.created_at) ?? now;
  const targetRecordId = nullableText(app.target_dns_record_id);
  sql.push(
    `INSERT OR IGNORE INTO applications (id, user_id, request_type, target_dns_record_id, subdomain, record_type, record_value, purpose, status, admin_notes, ttl, proxied, voting_deadline_at, telegram_message_id, created_at, updated_at) VALUES (${values([
      `app_old_${app.id}`,
      `usr_old_${app.user_id}`,
      normalizeRequestType(app.request_type),
      targetRecordId && legacyRecordIds.has(targetRecordId) ? targetRecordId : null,
      fallbackText(app.subdomain, `invalid-${app.id}`),
      normalizeRecordType(app.record_type),
      fallbackText(app.record_value, "0.0.0.0"),
      nullableText(app.purpose),
      normalizeApplicationStatus(app.status),
      appendMissingTargetNote(app.admin_notes, normalizeRequestType(app.request_type), targetRecordId, legacyRecordIds),
      normalizeInteger(app.ttl, 3600),
      isTruthy(app.proxied) ? 1 : 0,
      asTimestamp(app.voting_deadline_at) ?? createdAt,
      nullableText(app.telegram_message_id),
      createdAt,
      createdAt,
    ])});`,
  );
}

const votes = readAll<Record<string, unknown>>("SELECT * FROM application_votes ORDER BY id");
for (const vote of votes) {
  const admin = users.find((user) => String(user.telegram_user_id ?? "") === String(vote.admin_telegram_user_id ?? ""));
  if (!admin) continue;
  sql.push(
    `INSERT OR IGNORE INTO application_votes (id, application_id, admin_user_id, admin_telegram_user_id, vote_type, source, created_at) VALUES (${values([
      `vote_old_${vote.id}`,
      `app_old_${vote.application_id}`,
      `usr_old_${admin.id}`,
      fallbackText(vote.admin_telegram_user_id, "unknown"),
      vote.vote_type === "approve" ? "approve" : "deny",
      "telegram",
      asTimestamp(vote.created_at) ?? now,
    ])});`,
  );
}

const reports = readAll<Record<string, unknown>>("SELECT * FROM abuse_reports ORDER BY id");
for (const report of reports) {
  const createdAt = asTimestamp(report.created_at) ?? now;
  sql.push(
    `INSERT OR IGNORE INTO abuse_reports (id, subdomain, reason, details, reporter_ip, status, telegram_message_id, created_at, updated_at) VALUES (${values([
      `abr_old_${report.id}`,
      fallbackText(report.subdomain, "invalid"),
      fallbackText(report.reason, "unknown"),
      nullableText(report.details),
      nullableText(report.reporter_ip),
      normalizeReportStatus(report.status),
      nullableText(report.telegram_message_id),
      createdAt,
      createdAt,
    ])});`,
  );
}

sql.push("COMMIT;", "PRAGMA foreign_keys = ON;");
mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, `${sql.join("\n")}\n`);
console.log(`Wrote ${outputPath}`);
console.log(`Source: ${oldDbPath}`);
console.log(`Users: ${users.length}, Records: ${records.length}, Applications: ${applications.length}, Votes: ${votes.length}, Reports: ${reports.length}`);

function readAll<T>(query: string): T[] {
  try {
    return db.prepare(query).all() as T[];
  } catch {
    return [];
  }
}

function values(items: unknown[]) {
  return items.map(escapeSql).join(", ");
}

function escapeSql(value: unknown) {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "number") return Number.isFinite(value) ? String(value) : "NULL";
  return `'${String(value).replace(/'/g, "''")}'`;
}

function nullableText(value: unknown) {
  if (value === null || value === undefined) return null;
  const text = String(value).trim();
  return text.length ? text : null;
}

function fallbackText(value: unknown, fallback: string) {
  return nullableText(value) ?? fallback;
}

function normalizeLegacyEmail(email: unknown, username: unknown, id: unknown) {
  const normalized = nullableText(email);
  if (normalized) return normalized;
  const safeUser = fallbackText(username, `legacy-user-${id}`).replace(/[^a-zA-Z0-9._-]/g, "-");
  return `${safeUser}@legacy.invalid`;
}

function normalizeRole(value: unknown) {
  return value === "admin" ? "admin" : "user";
}

function normalizeInteger(value: unknown, fallback: number) {
  const numeric = Number(value);
  return Number.isFinite(numeric) ? Math.trunc(numeric) : fallback;
}

function isTruthy(value: unknown) {
  return value === true || value === 1 || value === "1" || value === "true";
}

function asTimestamp(value: unknown) {
  const text = nullableText(value);
  return text ?? null;
}

function normalizeRequestType(value: unknown) {
  return value === "update" ? "update" : "create";
}

function normalizeRecordType(value: unknown) {
  const type = String(value ?? "").toUpperCase();
  return ["A", "AAAA", "CNAME", "TXT"].includes(type) ? type : "A";
}

function normalizeApplicationStatus(value: unknown) {
  const status = String(value ?? "pending").toLowerCase();
  return ["pending", "approved", "rejected", "expired", "error"].includes(status) ? status : "pending";
}

function normalizeReportStatus(value: unknown) {
  const status = String(value ?? "new").toLowerCase();
  return ["new", "acknowledged", "resolved", "ignored"].includes(status) ? status : "new";
}

function appendMissingTargetNote(notes: unknown, requestType: string, targetRecordId: string | null, recordIds: Set<string>) {
  const base = nullableText(notes);
  if (requestType !== "update" || !targetRecordId || recordIds.has(targetRecordId)) return base;
  const extra = `Legacy target record missing during migration: ${targetRecordId}`;
  return base ? `${base} | ${extra}` : extra;
}
